### ISSUE TITLE
[EPIC] Revalidation

### ISSUE THREAD

**Issue by TurnipXenon** [TurnipXenon/potato#33]
https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration

- [x] Make endpoint at potato #34
- [x] Call this endpoint from turnip https://github.com/TurnipXenon/turnip/issues/116
- [x] Create UI in potato to call turnip to make validation #35
- [x] Setup the environment variables both in Turnip and Potato?
  - [x] Potato: TURNIP_TOKEN, SERVICE_NAME
  - [x] Turnip: POTATO_TOKEN, POTATO_URL
- [ ] #48

**Comment by TurnipXenon** [comment]
Moving upgrading to NextJs13 later when it's more stable
